@startuml

!include <azure/AzureCommon.puml>
!include <azure/AzureSimplified.puml>
!include <azure/Management/AzureAutomation.puml>
!include <azure/Storage/AzureDataLakeStorage.puml>
!include <azure/Databases/AzureDatabaseForPostgreSQL.puml>
!include <azure/Storage/AzureFileStorage.puml>
!include <azure/Web/AzureCDN.puml>
!include <azure/Databases/AzureSqlStretchDatabase.puml>

!include <cloudinsight/windows>

left to right direction

skinparam handwritten true
skinparam monochrome true
skinparam packageStyle rect
skinparam defaultFontName Habel
skinparam defaultFontName Plume
skinparam defaultFontSize 30
skinparam defaultFontColor Grey
skinparam shadowing false

@enduml